#!/bin/bash

# Enable port forwarding
sudo sed -i '/^#net.ipv4.ip_forward=1/s/^#//' /etc/ufw/sysctl.conf
sudo sed -i '/^net.ipv4.ip_forward=0/s/0/1/' /etc/ufw/sysctl.conf

# Add port forwarding rule
sudo sed -i '/^*filter/i \
*nat\n\
:PREROUTING ACCEPT [0:0]\n\
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\n\
COMMIT\n' /etc/ufw/before.rules

# Reload ufw
sudo ufw disable
sudo ufw enable

