#!/bin/bash
# This script configures the firewall to forward port 8080/TCP to port 80/TCP on web-01.

# Add a rule to forward port 8080 to 80
sudo ufw allow 8080/tcp
sudo ufw route allow proto tcp from any to any port 8080
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80

# Enable UFW if not enabled
sudo ufw enable

